/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentBar: typeof import('./components/AgentBar.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCode: typeof import('naive-ui')['NCode']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NH2: typeof import('naive-ui')['NH2']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NovelCard: typeof import('./components/NovelCard.vue')['default']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    OutlineTree: typeof import('./components/OutlineTree.vue')['default']
    PhaseAccordion: typeof import('./components/PhaseAccordion.vue')['default']
    RoleEditor: typeof import('./components/RoleEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextEditor: typeof import('./components/TextEditor.vue')['default']
    TocPanel: typeof import('./components/TocPanel.vue')['default']
    UnlockDialog: typeof import('./components/UnlockDialog.vue')['default']
  }
}

// For TSX support
declare global {
  const AgentBar: typeof import('./components/AgentBar.vue')['default']
  const NAlert: typeof import('naive-ui')['NAlert']
  const NButton: typeof import('naive-ui')['NButton']
  const NButtonGroup: typeof import('naive-ui')['NButtonGroup']
  const NCard: typeof import('naive-ui')['NCard']
  const NCode: typeof import('naive-ui')['NCode']
  const NCollapse: typeof import('naive-ui')['NCollapse']
  const NCollapseItem: typeof import('naive-ui')['NCollapseItem']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDivider: typeof import('naive-ui')['NDivider']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NGrid: typeof import('naive-ui')['NGrid']
  const NGridItem: typeof import('naive-ui')['NGridItem']
  const NH2: typeof import('naive-ui')['NH2']
  const NInput: typeof import('naive-ui')['NInput']
  const NInputNumber: typeof import('naive-ui')['NInputNumber']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutContent: typeof import('naive-ui')['NLayoutContent']
  const NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
  const NLayoutSider: typeof import('naive-ui')['NLayoutSider']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NModal: typeof import('naive-ui')['NModal']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const NovelCard: typeof import('./components/NovelCard.vue')['default']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NSpin: typeof import('naive-ui')['NSpin']
  const NTag: typeof import('naive-ui')['NTag']
  const OutlineTree: typeof import('./components/OutlineTree.vue')['default']
  const PhaseAccordion: typeof import('./components/PhaseAccordion.vue')['default']
  const RoleEditor: typeof import('./components/RoleEditor.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TextEditor: typeof import('./components/TextEditor.vue')['default']
  const TocPanel: typeof import('./components/TocPanel.vue')['default']
  const UnlockDialog: typeof import('./components/UnlockDialog.vue')['default']
}